/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MediaIndexRouteImport } from './routes/media.index'
import { Route as ContentTypesIndexRouteImport } from './routes/content-types.index'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as ContentTypesNewRouteImport } from './routes/content-types.new'
import { Route as ContentTypesApiIdRouteImport } from './routes/content-types.$apiId'
import { Route as ArticlesNewRouteImport } from './routes/articles.new'
import { Route as ArticlesIdRouteImport } from './routes/articles.$id'
import { Route as ContentApiIdIndexRouteImport } from './routes/content.$apiId.index'
import { Route as ContentApiIdNewRouteImport } from './routes/content.$apiId.new'
import { Route as ContentApiIdIdRouteImport } from './routes/content.$apiId.$id'
import { Route as ArticlesIdEditRouteImport } from './routes/articles.$id.edit'
import { Route as ContentApiIdIdEditRouteImport } from './routes/content.$apiId.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaIndexRoute = MediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentTypesIndexRoute = ContentTypesIndexRouteImport.update({
  id: '/content-types/',
  path: '/content-types/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentTypesNewRoute = ContentTypesNewRouteImport.update({
  id: '/content-types/new',
  path: '/content-types/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentTypesApiIdRoute = ContentTypesApiIdRouteImport.update({
  id: '/content-types/$apiId',
  path: '/content-types/$apiId',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesNewRoute = ArticlesNewRouteImport.update({
  id: '/articles/new',
  path: '/articles/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIdRoute = ArticlesIdRouteImport.update({
  id: '/articles/$id',
  path: '/articles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentApiIdIndexRoute = ContentApiIdIndexRouteImport.update({
  id: '/content/$apiId/',
  path: '/content/$apiId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentApiIdNewRoute = ContentApiIdNewRouteImport.update({
  id: '/content/$apiId/new',
  path: '/content/$apiId/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentApiIdIdRoute = ContentApiIdIdRouteImport.update({
  id: '/content/$apiId/$id',
  path: '/content/$apiId/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIdEditRoute = ArticlesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ArticlesIdRoute,
} as any)
const ContentApiIdIdEditRoute = ContentApiIdIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ContentApiIdIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/articles/$id': typeof ArticlesIdRouteWithChildren
  '/articles/new': typeof ArticlesNewRoute
  '/content-types/$apiId': typeof ContentTypesApiIdRoute
  '/content-types/new': typeof ContentTypesNewRoute
  '/articles/': typeof ArticlesIndexRoute
  '/content-types/': typeof ContentTypesIndexRoute
  '/media/': typeof MediaIndexRoute
  '/articles/$id/edit': typeof ArticlesIdEditRoute
  '/content/$apiId/$id': typeof ContentApiIdIdRouteWithChildren
  '/content/$apiId/new': typeof ContentApiIdNewRoute
  '/content/$apiId/': typeof ContentApiIdIndexRoute
  '/content/$apiId/$id/edit': typeof ContentApiIdIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/articles/$id': typeof ArticlesIdRouteWithChildren
  '/articles/new': typeof ArticlesNewRoute
  '/content-types/$apiId': typeof ContentTypesApiIdRoute
  '/content-types/new': typeof ContentTypesNewRoute
  '/articles': typeof ArticlesIndexRoute
  '/content-types': typeof ContentTypesIndexRoute
  '/media': typeof MediaIndexRoute
  '/articles/$id/edit': typeof ArticlesIdEditRoute
  '/content/$apiId/$id': typeof ContentApiIdIdRouteWithChildren
  '/content/$apiId/new': typeof ContentApiIdNewRoute
  '/content/$apiId': typeof ContentApiIdIndexRoute
  '/content/$apiId/$id/edit': typeof ContentApiIdIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/articles/$id': typeof ArticlesIdRouteWithChildren
  '/articles/new': typeof ArticlesNewRoute
  '/content-types/$apiId': typeof ContentTypesApiIdRoute
  '/content-types/new': typeof ContentTypesNewRoute
  '/articles/': typeof ArticlesIndexRoute
  '/content-types/': typeof ContentTypesIndexRoute
  '/media/': typeof MediaIndexRoute
  '/articles/$id/edit': typeof ArticlesIdEditRoute
  '/content/$apiId/$id': typeof ContentApiIdIdRouteWithChildren
  '/content/$apiId/new': typeof ContentApiIdNewRoute
  '/content/$apiId/': typeof ContentApiIdIndexRoute
  '/content/$apiId/$id/edit': typeof ContentApiIdIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/articles/$id'
    | '/articles/new'
    | '/content-types/$apiId'
    | '/content-types/new'
    | '/articles/'
    | '/content-types/'
    | '/media/'
    | '/articles/$id/edit'
    | '/content/$apiId/$id'
    | '/content/$apiId/new'
    | '/content/$apiId/'
    | '/content/$apiId/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/articles/$id'
    | '/articles/new'
    | '/content-types/$apiId'
    | '/content-types/new'
    | '/articles'
    | '/content-types'
    | '/media'
    | '/articles/$id/edit'
    | '/content/$apiId/$id'
    | '/content/$apiId/new'
    | '/content/$apiId'
    | '/content/$apiId/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/articles/$id'
    | '/articles/new'
    | '/content-types/$apiId'
    | '/content-types/new'
    | '/articles/'
    | '/content-types/'
    | '/media/'
    | '/articles/$id/edit'
    | '/content/$apiId/$id'
    | '/content/$apiId/new'
    | '/content/$apiId/'
    | '/content/$apiId/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArticlesIdRoute: typeof ArticlesIdRouteWithChildren
  ArticlesNewRoute: typeof ArticlesNewRoute
  ContentTypesApiIdRoute: typeof ContentTypesApiIdRoute
  ContentTypesNewRoute: typeof ContentTypesNewRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  ContentTypesIndexRoute: typeof ContentTypesIndexRoute
  MediaIndexRoute: typeof MediaIndexRoute
  ContentApiIdIdRoute: typeof ContentApiIdIdRouteWithChildren
  ContentApiIdNewRoute: typeof ContentApiIdNewRoute
  ContentApiIdIndexRoute: typeof ContentApiIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/': {
      id: '/media/'
      path: '/media'
      fullPath: '/media/'
      preLoaderRoute: typeof MediaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-types/': {
      id: '/content-types/'
      path: '/content-types'
      fullPath: '/content-types/'
      preLoaderRoute: typeof ContentTypesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-types/new': {
      id: '/content-types/new'
      path: '/content-types/new'
      fullPath: '/content-types/new'
      preLoaderRoute: typeof ContentTypesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-types/$apiId': {
      id: '/content-types/$apiId'
      path: '/content-types/$apiId'
      fullPath: '/content-types/$apiId'
      preLoaderRoute: typeof ContentTypesApiIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/new': {
      id: '/articles/new'
      path: '/articles/new'
      fullPath: '/articles/new'
      preLoaderRoute: typeof ArticlesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$id': {
      id: '/articles/$id'
      path: '/articles/$id'
      fullPath: '/articles/$id'
      preLoaderRoute: typeof ArticlesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/$apiId/': {
      id: '/content/$apiId/'
      path: '/content/$apiId'
      fullPath: '/content/$apiId/'
      preLoaderRoute: typeof ContentApiIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/$apiId/new': {
      id: '/content/$apiId/new'
      path: '/content/$apiId/new'
      fullPath: '/content/$apiId/new'
      preLoaderRoute: typeof ContentApiIdNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/$apiId/$id': {
      id: '/content/$apiId/$id'
      path: '/content/$apiId/$id'
      fullPath: '/content/$apiId/$id'
      preLoaderRoute: typeof ContentApiIdIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$id/edit': {
      id: '/articles/$id/edit'
      path: '/edit'
      fullPath: '/articles/$id/edit'
      preLoaderRoute: typeof ArticlesIdEditRouteImport
      parentRoute: typeof ArticlesIdRoute
    }
    '/content/$apiId/$id/edit': {
      id: '/content/$apiId/$id/edit'
      path: '/edit'
      fullPath: '/content/$apiId/$id/edit'
      preLoaderRoute: typeof ContentApiIdIdEditRouteImport
      parentRoute: typeof ContentApiIdIdRoute
    }
  }
}

interface ArticlesIdRouteChildren {
  ArticlesIdEditRoute: typeof ArticlesIdEditRoute
}

const ArticlesIdRouteChildren: ArticlesIdRouteChildren = {
  ArticlesIdEditRoute: ArticlesIdEditRoute,
}

const ArticlesIdRouteWithChildren = ArticlesIdRoute._addFileChildren(
  ArticlesIdRouteChildren,
)

interface ContentApiIdIdRouteChildren {
  ContentApiIdIdEditRoute: typeof ContentApiIdIdEditRoute
}

const ContentApiIdIdRouteChildren: ContentApiIdIdRouteChildren = {
  ContentApiIdIdEditRoute: ContentApiIdIdEditRoute,
}

const ContentApiIdIdRouteWithChildren = ContentApiIdIdRoute._addFileChildren(
  ContentApiIdIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArticlesIdRoute: ArticlesIdRouteWithChildren,
  ArticlesNewRoute: ArticlesNewRoute,
  ContentTypesApiIdRoute: ContentTypesApiIdRoute,
  ContentTypesNewRoute: ContentTypesNewRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  ContentTypesIndexRoute: ContentTypesIndexRoute,
  MediaIndexRoute: MediaIndexRoute,
  ContentApiIdIdRoute: ContentApiIdIdRouteWithChildren,
  ContentApiIdNewRoute: ContentApiIdNewRoute,
  ContentApiIdIndexRoute: ContentApiIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
