/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthGalleryRouteImport } from './routes/auth-gallery'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModulesIndexRouteImport } from './routes/modules.index'
import { Route as MediaIndexRouteImport } from './routes/media.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as ModulesNewRouteImport } from './routes/modules.new'
import { Route as ModulesApiIdRouteImport } from './routes/modules.$apiId'
import { Route as ArticlesNewRouteImport } from './routes/articles.new'
import { Route as ArticlesIdRouteImport } from './routes/articles.$id'
import { Route as ContentApiIdIndexRouteImport } from './routes/content.$apiId.index'
import { Route as ContentApiIdNewRouteImport } from './routes/content.$apiId.new'
import { Route as ContentApiIdIdRouteImport } from './routes/content.$apiId.$id'
import { Route as ArticlesIdEditRouteImport } from './routes/articles.$id.edit'
import { Route as ContentApiIdIdEditRouteImport } from './routes/content.$apiId.$id.edit'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGalleryRoute = AuthGalleryRouteImport.update({
  id: '/auth-gallery',
  path: '/auth-gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesIndexRoute = ModulesIndexRouteImport.update({
  id: '/modules/',
  path: '/modules/',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaIndexRoute = MediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesNewRoute = ModulesNewRouteImport.update({
  id: '/modules/new',
  path: '/modules/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesApiIdRoute = ModulesApiIdRouteImport.update({
  id: '/modules/$apiId',
  path: '/modules/$apiId',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesNewRoute = ArticlesNewRouteImport.update({
  id: '/articles/new',
  path: '/articles/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIdRoute = ArticlesIdRouteImport.update({
  id: '/articles/$id',
  path: '/articles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentApiIdIndexRoute = ContentApiIdIndexRouteImport.update({
  id: '/content/$apiId/',
  path: '/content/$apiId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentApiIdNewRoute = ContentApiIdNewRouteImport.update({
  id: '/content/$apiId/new',
  path: '/content/$apiId/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentApiIdIdRoute = ContentApiIdIdRouteImport.update({
  id: '/content/$apiId/$id',
  path: '/content/$apiId/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIdEditRoute = ArticlesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ArticlesIdRoute,
} as any)
const ContentApiIdIdEditRoute = ContentApiIdIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ContentApiIdIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth-gallery': typeof AuthGalleryRoute
  '/sign-in': typeof SignInRoute
  '/articles/$id': typeof ArticlesIdRouteWithChildren
  '/articles/new': typeof ArticlesNewRoute
  '/modules/$apiId': typeof ModulesApiIdRoute
  '/modules/new': typeof ModulesNewRoute
  '/articles/': typeof ArticlesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/media/': typeof MediaIndexRoute
  '/modules/': typeof ModulesIndexRoute
  '/articles/$id/edit': typeof ArticlesIdEditRoute
  '/content/$apiId/$id': typeof ContentApiIdIdRouteWithChildren
  '/content/$apiId/new': typeof ContentApiIdNewRoute
  '/content/$apiId/': typeof ContentApiIdIndexRoute
  '/content/$apiId/$id/edit': typeof ContentApiIdIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth-gallery': typeof AuthGalleryRoute
  '/sign-in': typeof SignInRoute
  '/articles/$id': typeof ArticlesIdRouteWithChildren
  '/articles/new': typeof ArticlesNewRoute
  '/modules/$apiId': typeof ModulesApiIdRoute
  '/modules/new': typeof ModulesNewRoute
  '/articles': typeof ArticlesIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/media': typeof MediaIndexRoute
  '/modules': typeof ModulesIndexRoute
  '/articles/$id/edit': typeof ArticlesIdEditRoute
  '/content/$apiId/$id': typeof ContentApiIdIdRouteWithChildren
  '/content/$apiId/new': typeof ContentApiIdNewRoute
  '/content/$apiId': typeof ContentApiIdIndexRoute
  '/content/$apiId/$id/edit': typeof ContentApiIdIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth-gallery': typeof AuthGalleryRoute
  '/sign-in': typeof SignInRoute
  '/articles/$id': typeof ArticlesIdRouteWithChildren
  '/articles/new': typeof ArticlesNewRoute
  '/modules/$apiId': typeof ModulesApiIdRoute
  '/modules/new': typeof ModulesNewRoute
  '/articles/': typeof ArticlesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/media/': typeof MediaIndexRoute
  '/modules/': typeof ModulesIndexRoute
  '/articles/$id/edit': typeof ArticlesIdEditRoute
  '/content/$apiId/$id': typeof ContentApiIdIdRouteWithChildren
  '/content/$apiId/new': typeof ContentApiIdNewRoute
  '/content/$apiId/': typeof ContentApiIdIndexRoute
  '/content/$apiId/$id/edit': typeof ContentApiIdIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth-gallery'
    | '/sign-in'
    | '/articles/$id'
    | '/articles/new'
    | '/modules/$apiId'
    | '/modules/new'
    | '/articles/'
    | '/dashboard/'
    | '/media/'
    | '/modules/'
    | '/articles/$id/edit'
    | '/content/$apiId/$id'
    | '/content/$apiId/new'
    | '/content/$apiId/'
    | '/content/$apiId/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth-gallery'
    | '/sign-in'
    | '/articles/$id'
    | '/articles/new'
    | '/modules/$apiId'
    | '/modules/new'
    | '/articles'
    | '/dashboard'
    | '/media'
    | '/modules'
    | '/articles/$id/edit'
    | '/content/$apiId/$id'
    | '/content/$apiId/new'
    | '/content/$apiId'
    | '/content/$apiId/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/auth-gallery'
    | '/sign-in'
    | '/articles/$id'
    | '/articles/new'
    | '/modules/$apiId'
    | '/modules/new'
    | '/articles/'
    | '/dashboard/'
    | '/media/'
    | '/modules/'
    | '/articles/$id/edit'
    | '/content/$apiId/$id'
    | '/content/$apiId/new'
    | '/content/$apiId/'
    | '/content/$apiId/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthGalleryRoute: typeof AuthGalleryRoute
  SignInRoute: typeof SignInRoute
  ArticlesIdRoute: typeof ArticlesIdRouteWithChildren
  ArticlesNewRoute: typeof ArticlesNewRoute
  ModulesApiIdRoute: typeof ModulesApiIdRoute
  ModulesNewRoute: typeof ModulesNewRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  MediaIndexRoute: typeof MediaIndexRoute
  ModulesIndexRoute: typeof ModulesIndexRoute
  ContentApiIdIdRoute: typeof ContentApiIdIdRouteWithChildren
  ContentApiIdNewRoute: typeof ContentApiIdNewRoute
  ContentApiIdIndexRoute: typeof ContentApiIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-gallery': {
      id: '/auth-gallery'
      path: '/auth-gallery'
      fullPath: '/auth-gallery'
      preLoaderRoute: typeof AuthGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/': {
      id: '/modules/'
      path: '/modules'
      fullPath: '/modules/'
      preLoaderRoute: typeof ModulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/': {
      id: '/media/'
      path: '/media'
      fullPath: '/media/'
      preLoaderRoute: typeof MediaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/new': {
      id: '/modules/new'
      path: '/modules/new'
      fullPath: '/modules/new'
      preLoaderRoute: typeof ModulesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/$apiId': {
      id: '/modules/$apiId'
      path: '/modules/$apiId'
      fullPath: '/modules/$apiId'
      preLoaderRoute: typeof ModulesApiIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/new': {
      id: '/articles/new'
      path: '/articles/new'
      fullPath: '/articles/new'
      preLoaderRoute: typeof ArticlesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$id': {
      id: '/articles/$id'
      path: '/articles/$id'
      fullPath: '/articles/$id'
      preLoaderRoute: typeof ArticlesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/$apiId/': {
      id: '/content/$apiId/'
      path: '/content/$apiId'
      fullPath: '/content/$apiId/'
      preLoaderRoute: typeof ContentApiIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/$apiId/new': {
      id: '/content/$apiId/new'
      path: '/content/$apiId/new'
      fullPath: '/content/$apiId/new'
      preLoaderRoute: typeof ContentApiIdNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/$apiId/$id': {
      id: '/content/$apiId/$id'
      path: '/content/$apiId/$id'
      fullPath: '/content/$apiId/$id'
      preLoaderRoute: typeof ContentApiIdIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$id/edit': {
      id: '/articles/$id/edit'
      path: '/edit'
      fullPath: '/articles/$id/edit'
      preLoaderRoute: typeof ArticlesIdEditRouteImport
      parentRoute: typeof ArticlesIdRoute
    }
    '/content/$apiId/$id/edit': {
      id: '/content/$apiId/$id/edit'
      path: '/edit'
      fullPath: '/content/$apiId/$id/edit'
      preLoaderRoute: typeof ContentApiIdIdEditRouteImport
      parentRoute: typeof ContentApiIdIdRoute
    }
  }
}

interface ArticlesIdRouteChildren {
  ArticlesIdEditRoute: typeof ArticlesIdEditRoute
}

const ArticlesIdRouteChildren: ArticlesIdRouteChildren = {
  ArticlesIdEditRoute: ArticlesIdEditRoute,
}

const ArticlesIdRouteWithChildren = ArticlesIdRoute._addFileChildren(
  ArticlesIdRouteChildren,
)

interface ContentApiIdIdRouteChildren {
  ContentApiIdIdEditRoute: typeof ContentApiIdIdEditRoute
}

const ContentApiIdIdRouteChildren: ContentApiIdIdRouteChildren = {
  ContentApiIdIdEditRoute: ContentApiIdIdEditRoute,
}

const ContentApiIdIdRouteWithChildren = ContentApiIdIdRoute._addFileChildren(
  ContentApiIdIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthGalleryRoute: AuthGalleryRoute,
  SignInRoute: SignInRoute,
  ArticlesIdRoute: ArticlesIdRouteWithChildren,
  ArticlesNewRoute: ArticlesNewRoute,
  ModulesApiIdRoute: ModulesApiIdRoute,
  ModulesNewRoute: ModulesNewRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  MediaIndexRoute: MediaIndexRoute,
  ModulesIndexRoute: ModulesIndexRoute,
  ContentApiIdIdRoute: ContentApiIdIdRouteWithChildren,
  ContentApiIdNewRoute: ContentApiIdNewRoute,
  ContentApiIdIndexRoute: ContentApiIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
