/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthGalleryRouteImport } from './routes/auth-gallery'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModulesIndexRouteImport } from './routes/modules.index'
import { Route as MediaIndexRouteImport } from './routes/media.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as ModulesNewRouteImport } from './routes/modules.new'
import { Route as ModulesNameRouteImport } from './routes/modules.$name'
import { Route as ArticlesNewRouteImport } from './routes/articles.new'
import { Route as ArticlesIdRouteImport } from './routes/articles.$id'
import { Route as ContentNameIndexRouteImport } from './routes/content.$name.index'
import { Route as ContentNameNewRouteImport } from './routes/content.$name.new'
import { Route as ContentNameIdRouteImport } from './routes/content.$name.$id'
import { Route as ArticlesIdEditRouteImport } from './routes/articles.$id.edit'
import { Route as ContentNameIdEditRouteImport } from './routes/content.$name.$id.edit'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGalleryRoute = AuthGalleryRouteImport.update({
  id: '/auth-gallery',
  path: '/auth-gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesIndexRoute = ModulesIndexRouteImport.update({
  id: '/modules/',
  path: '/modules/',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaIndexRoute = MediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesNewRoute = ModulesNewRouteImport.update({
  id: '/modules/new',
  path: '/modules/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesNameRoute = ModulesNameRouteImport.update({
  id: '/modules/$name',
  path: '/modules/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesNewRoute = ArticlesNewRouteImport.update({
  id: '/articles/new',
  path: '/articles/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIdRoute = ArticlesIdRouteImport.update({
  id: '/articles/$id',
  path: '/articles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentNameIndexRoute = ContentNameIndexRouteImport.update({
  id: '/content/$name/',
  path: '/content/$name/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentNameNewRoute = ContentNameNewRouteImport.update({
  id: '/content/$name/new',
  path: '/content/$name/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentNameIdRoute = ContentNameIdRouteImport.update({
  id: '/content/$name/$id',
  path: '/content/$name/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIdEditRoute = ArticlesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ArticlesIdRoute,
} as any)
const ContentNameIdEditRoute = ContentNameIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ContentNameIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth-gallery': typeof AuthGalleryRoute
  '/sign-in': typeof SignInRoute
  '/articles/$id': typeof ArticlesIdRouteWithChildren
  '/articles/new': typeof ArticlesNewRoute
  '/modules/$name': typeof ModulesNameRoute
  '/modules/new': typeof ModulesNewRoute
  '/articles/': typeof ArticlesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/media/': typeof MediaIndexRoute
  '/modules/': typeof ModulesIndexRoute
  '/articles/$id/edit': typeof ArticlesIdEditRoute
  '/content/$name/$id': typeof ContentNameIdRouteWithChildren
  '/content/$name/new': typeof ContentNameNewRoute
  '/content/$name/': typeof ContentNameIndexRoute
  '/content/$name/$id/edit': typeof ContentNameIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth-gallery': typeof AuthGalleryRoute
  '/sign-in': typeof SignInRoute
  '/articles/$id': typeof ArticlesIdRouteWithChildren
  '/articles/new': typeof ArticlesNewRoute
  '/modules/$name': typeof ModulesNameRoute
  '/modules/new': typeof ModulesNewRoute
  '/articles': typeof ArticlesIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/media': typeof MediaIndexRoute
  '/modules': typeof ModulesIndexRoute
  '/articles/$id/edit': typeof ArticlesIdEditRoute
  '/content/$name/$id': typeof ContentNameIdRouteWithChildren
  '/content/$name/new': typeof ContentNameNewRoute
  '/content/$name': typeof ContentNameIndexRoute
  '/content/$name/$id/edit': typeof ContentNameIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth-gallery': typeof AuthGalleryRoute
  '/sign-in': typeof SignInRoute
  '/articles/$id': typeof ArticlesIdRouteWithChildren
  '/articles/new': typeof ArticlesNewRoute
  '/modules/$name': typeof ModulesNameRoute
  '/modules/new': typeof ModulesNewRoute
  '/articles/': typeof ArticlesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/media/': typeof MediaIndexRoute
  '/modules/': typeof ModulesIndexRoute
  '/articles/$id/edit': typeof ArticlesIdEditRoute
  '/content/$name/$id': typeof ContentNameIdRouteWithChildren
  '/content/$name/new': typeof ContentNameNewRoute
  '/content/$name/': typeof ContentNameIndexRoute
  '/content/$name/$id/edit': typeof ContentNameIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth-gallery'
    | '/sign-in'
    | '/articles/$id'
    | '/articles/new'
    | '/modules/$name'
    | '/modules/new'
    | '/articles/'
    | '/dashboard/'
    | '/media/'
    | '/modules/'
    | '/articles/$id/edit'
    | '/content/$name/$id'
    | '/content/$name/new'
    | '/content/$name/'
    | '/content/$name/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth-gallery'
    | '/sign-in'
    | '/articles/$id'
    | '/articles/new'
    | '/modules/$name'
    | '/modules/new'
    | '/articles'
    | '/dashboard'
    | '/media'
    | '/modules'
    | '/articles/$id/edit'
    | '/content/$name/$id'
    | '/content/$name/new'
    | '/content/$name'
    | '/content/$name/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/auth-gallery'
    | '/sign-in'
    | '/articles/$id'
    | '/articles/new'
    | '/modules/$name'
    | '/modules/new'
    | '/articles/'
    | '/dashboard/'
    | '/media/'
    | '/modules/'
    | '/articles/$id/edit'
    | '/content/$name/$id'
    | '/content/$name/new'
    | '/content/$name/'
    | '/content/$name/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthGalleryRoute: typeof AuthGalleryRoute
  SignInRoute: typeof SignInRoute
  ArticlesIdRoute: typeof ArticlesIdRouteWithChildren
  ArticlesNewRoute: typeof ArticlesNewRoute
  ModulesNameRoute: typeof ModulesNameRoute
  ModulesNewRoute: typeof ModulesNewRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  MediaIndexRoute: typeof MediaIndexRoute
  ModulesIndexRoute: typeof ModulesIndexRoute
  ContentNameIdRoute: typeof ContentNameIdRouteWithChildren
  ContentNameNewRoute: typeof ContentNameNewRoute
  ContentNameIndexRoute: typeof ContentNameIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-gallery': {
      id: '/auth-gallery'
      path: '/auth-gallery'
      fullPath: '/auth-gallery'
      preLoaderRoute: typeof AuthGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/': {
      id: '/modules/'
      path: '/modules'
      fullPath: '/modules/'
      preLoaderRoute: typeof ModulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/': {
      id: '/media/'
      path: '/media'
      fullPath: '/media/'
      preLoaderRoute: typeof MediaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/new': {
      id: '/modules/new'
      path: '/modules/new'
      fullPath: '/modules/new'
      preLoaderRoute: typeof ModulesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/$name': {
      id: '/modules/$name'
      path: '/modules/$name'
      fullPath: '/modules/$name'
      preLoaderRoute: typeof ModulesNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/new': {
      id: '/articles/new'
      path: '/articles/new'
      fullPath: '/articles/new'
      preLoaderRoute: typeof ArticlesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$id': {
      id: '/articles/$id'
      path: '/articles/$id'
      fullPath: '/articles/$id'
      preLoaderRoute: typeof ArticlesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/$name/': {
      id: '/content/$name/'
      path: '/content/$name'
      fullPath: '/content/$name/'
      preLoaderRoute: typeof ContentNameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/$name/new': {
      id: '/content/$name/new'
      path: '/content/$name/new'
      fullPath: '/content/$name/new'
      preLoaderRoute: typeof ContentNameNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/$name/$id': {
      id: '/content/$name/$id'
      path: '/content/$name/$id'
      fullPath: '/content/$name/$id'
      preLoaderRoute: typeof ContentNameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$id/edit': {
      id: '/articles/$id/edit'
      path: '/edit'
      fullPath: '/articles/$id/edit'
      preLoaderRoute: typeof ArticlesIdEditRouteImport
      parentRoute: typeof ArticlesIdRoute
    }
    '/content/$name/$id/edit': {
      id: '/content/$name/$id/edit'
      path: '/edit'
      fullPath: '/content/$name/$id/edit'
      preLoaderRoute: typeof ContentNameIdEditRouteImport
      parentRoute: typeof ContentNameIdRoute
    }
  }
}

interface ArticlesIdRouteChildren {
  ArticlesIdEditRoute: typeof ArticlesIdEditRoute
}

const ArticlesIdRouteChildren: ArticlesIdRouteChildren = {
  ArticlesIdEditRoute: ArticlesIdEditRoute,
}

const ArticlesIdRouteWithChildren = ArticlesIdRoute._addFileChildren(
  ArticlesIdRouteChildren,
)

interface ContentNameIdRouteChildren {
  ContentNameIdEditRoute: typeof ContentNameIdEditRoute
}

const ContentNameIdRouteChildren: ContentNameIdRouteChildren = {
  ContentNameIdEditRoute: ContentNameIdEditRoute,
}

const ContentNameIdRouteWithChildren = ContentNameIdRoute._addFileChildren(
  ContentNameIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthGalleryRoute: AuthGalleryRoute,
  SignInRoute: SignInRoute,
  ArticlesIdRoute: ArticlesIdRouteWithChildren,
  ArticlesNewRoute: ArticlesNewRoute,
  ModulesNameRoute: ModulesNameRoute,
  ModulesNewRoute: ModulesNewRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  MediaIndexRoute: MediaIndexRoute,
  ModulesIndexRoute: ModulesIndexRoute,
  ContentNameIdRoute: ContentNameIdRouteWithChildren,
  ContentNameNewRoute: ContentNameNewRoute,
  ContentNameIndexRoute: ContentNameIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
