import type { Schema, FieldSchema, RelationSchema } from './model.ts';
import { AppError } from '../../errors/app-error.ts';

/** Raised when the codegen meets a field kind the v1 DSL can't yet express (e.g. repeatable components). */
export class BuilderCodegenError extends AppError {
  constructor(message: string) {
    super('db.schema.codegen', { detail: message });
  }
}

/**
 * CODEGEN (the S2 function, folded into S5): JSON schema files are the SOURCE; TS types are GENERATED from
 * them — never hand-authored. {@link generateTypes} is a PURE `schemas -> .d.ts string` (no DB, no fs); the
 * Builder calls it as a side-effect of rewriting a schema file, and `conti gen:types --check` uses it as a
 * CI freshness gate. Keeping JSON as the truth + types as a derived artifact is the "best of both" the
 * design doc settled on (JSON truth + generated types, never fragile hand-written generics).
 *
 * The mapping is the WIRE/read shape: every field's JSON key is its `name` (verbatim — the engine never
 * snake_cases), an i64/decimal serialize as STRINGS (byte-exact big numbers), an enumeration narrows to a
 * literal union, and a nullable field is `name?: T | null`. Component/dynamiczone/relation/json map to
 * `unknown` for now (the nested-shape generation lands with relation+component files-path support).
 */

/** PascalCase a snake/kebab name for the interface name (`blog_post` -> `BlogPost`, `article` -> `Article`). */
function pascalCase(s: string): string {
  return s.replace(/(^|[_-])([a-zA-Z0-9])/g, (_m, _sep, c: string) => c.toUpperCase());
}

/** The TS type for one field, from its CmsType (+ enum members / media cardinality). */
function tsTypeOf(f: FieldSchema): string {
  switch (f.type) {
    case 'string':
    case 'text':
    case 'email':
    case 'uid':
    case 'uuid':
    case 'date':
    case 'datetime':
    case 'time':
      return 'string';
    case 'biginteger':
    case 'decimal':
      return 'string'; // i64 / numeric serialize as strings (byte-exact, no float precision loss)
    case 'enumeration': {
      const values = f.options?.values;
      return Array.isArray(values) && values.length > 0 ? values.map((v) => JSON.stringify(v)).join(' | ') : 'string';
    }
    case 'integer':
    case 'float':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'media':
      return f.options?.multiple ? 'number[]' : 'number'; // un-populated: the referenced files.id(s)
    case 'json':
    case 'array':
    case 'component':
    case 'component-repeatable':
    case 'dynamiczone':
    case 'relation':
      return 'unknown'; // nested-shape generation deferred with the relation+component files-path slice
  }
}

function fieldLine(f: FieldSchema): string {
  const nullable = f.options?.nullable ?? true;
  const t = tsTypeOf(f);
  return nullable ? `  ${f.name}?: ${t} | null;` : `  ${f.name}: ${t};`;
}

/**
 * Generate the `modules.d.ts` text for a catalog of schemas (sorted by name for a deterministic,
 * diff-stable artifact). One interface per module: the system fields the read path always emits,
 * then the user fields in declared (wire) order.
 */
export function generateTypes(schemas: Schema[]): string {
  const header =
    '// GENERATED by conti — do not edit by hand. Source of truth: schema/*.json\n' +
    '// Regenerate with `conti gen:types` after editing a schema file.\n\n';

  const blocks = [...schemas]
    .sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0))
    .map((s) => {
      const lines: string[] = [`export interface ${pascalCase(s.name)} {`, '  id: number;'];
      if (s.options?.i18n) lines.push('  document_id: number;');
      lines.push('  created_at: string;', '  updated_at: string;');
      if (s.options?.draftAndPublish) lines.push('  published_at?: string | null;');
      if (s.options?.i18n) lines.push('  locale: string;');
      for (const f of s.fields) lines.push(fieldLine(f));
      lines.push('}');
      return lines.join('\n');
    });

  return header + blocks.join('\n\n') + '\n';
}

// --- DSL SOURCE codegen (the visual Builder's writer: IR -> modules/<name>/schema.ts) ----------

/** A JSON-ish literal for embedding in generated source (strings double-quoted, arrays inline). */
function lit(v: unknown): string {
  return JSON.stringify(v);
}

/** The `c.*(...)` builder call for one field — the inverse of `defToSchema` + the catalog resolution. */
function fieldBuilderCall(f: FieldSchema): string {
  const o = f.options ?? {};
  const id = `id: ${lit(f.id)}`;
  const nul = o.nullable === false ? ', nullable: false' : ''; // nullable defaults true ⇒ omit when true
  const def = o.default !== undefined ? `, default: ${lit(o.default)}` : '';
  const max = o.length !== undefined ? `, max: ${o.length}` : '';
  const min = o.min !== undefined ? `, min: ${o.min}` : '';
  // Common per-field metadata every type carries (editor layout + conditional visibility) — emit so it
  // round-trips through the file (the `info`/`label` lesson: an un-emitted option is silently lost on boot).
  const cm =
    (o.editorWidth !== undefined ? `, editorWidth: ${lit(o.editorWidth)}` : '') +
    (o.condition !== undefined ? `, condition: ${lit(o.condition)}` : '');
  switch (f.type) {
    case 'string': return `c.string({ ${id}${max}${min}${nul}${def}${cm} })`;
    case 'text': return `c.text({ ${id}${nul}${def}${cm} })`;
    case 'email': return `c.email({ ${id}${max}${min}${nul}${cm} })`;
    case 'uid': return `c.uid({ ${id}${max}${min}${nul}${cm} })`;
    case 'uuid': return `c.uuid({ ${id}${nul}${cm} })`;
    case 'enumeration': return `c.enum(${lit(o.values ?? [])} as const, { ${id}${nul}${cm} })`;
    case 'integer': return `c.integer({ ${id}${nul}${def}${cm} })`;
    case 'biginteger': return `c.biginteger({ ${id}${nul}${cm} })`;
    case 'float': return `c.float({ ${id}${nul}${def}${cm} })`;
    case 'decimal': return `c.decimal({ ${id}${o.precision !== undefined ? `, precision: ${o.precision}` : ''}${o.scale !== undefined ? `, scale: ${o.scale}` : ''}${nul}${cm} })`;
    case 'boolean': return `c.boolean({ ${id}${nul}${def}${cm} })`;
    case 'date': return `c.date({ ${id}${nul}${cm} })`;
    case 'datetime': return `c.datetime({ ${id}${nul}${cm} })`;
    case 'json': return `c.json({ ${id}${nul}${cm} })`;
    case 'media': return `c.media({ ${id}${o.multiple ? ', multiple: true' : ''}${nul}${cm} })`;
    case 'component': return `c.component(${lit(o.component ?? '')}, { ${id}${nul}${cm} })`;
    case 'dynamiczone': return `c.dynamiczone(${lit(o.components ?? [])}, { ${id} })`;
    default:
      throw new BuilderCodegenError(`field "${f.name}": type "${f.type}" is not yet expressible by the Builder codegen`);
  }
}

/** The `c.relation(...)` call for an owner relation. */
function relationBuilderCall(r: RelationSchema): string {
  const inv = r.inverseField !== undefined ? `, inverse: ${lit(r.inverseField)}` : '';
  const disp = r.displayField !== undefined ? `, displayField: ${lit(r.displayField)}` : '';
  return `c.relation(${lit(r.target)}, { id: ${lit(r.id)}, kind: ${lit(r.kind)}${inv}${disp} })`;
}

/**
 * Generate the full `modules/<name>/schema.ts` SOURCE from the IR — the visual Builder's write artifact.
 * Pure: IR in, source string out. Round-trips: loading the generated file (`loadTypes` → `defToSchema`)
 * yields an IR equal to the input. The Builder regenerates this file WHOLESALE; hooks live in the sibling
 * `hooks.ts` and are never touched.
 */
export function generateSchemaSource(schema: Schema): string {
  const name = pascalCase(schema.name);
  const lines: string[] = ["import { defineSchema, c } from '@conti/core';", '', `const ${name} = defineSchema({`, `  id: ${lit(schema.id)},`];
  if (schema.label !== undefined) lines.push(`  label: ${lit(schema.label)},`);
  if (schema.options !== undefined) {
    const parts: string[] = [];
    if (schema.options.draftAndPublish !== undefined) parts.push(`draftAndPublish: ${schema.options.draftAndPublish}`);
    if (schema.options.i18n !== undefined) parts.push(`i18n: ${schema.options.i18n}`);
    if (parts.length > 0) lines.push(`  options: { ${parts.join(', ')} },`);
  }
  lines.push('  fields: {');
  for (const f of schema.fields) lines.push(`    ${f.name}: ${fieldBuilderCall(f)},`);
  for (const r of schema.relations ?? []) lines.push(`    ${r.field}: ${relationBuilderCall(r)},`);
  lines.push('  },', '});', '', `export default ${name};`, `export type ${name} = typeof ${name};`, '');
  return lines.join('\n');
}
