import type { ContentTypeSchema, FieldSchema } from './model.ts';

/**
 * CODEGEN (the S2 function, folded into S5): JSON schema files are the SOURCE; TS types are GENERATED from
 * them — never hand-authored. {@link generateTypes} is a PURE `schemas -> .d.ts string` (no DB, no fs); the
 * Builder calls it as a side-effect of rewriting a schema file, and `conti gen:types --check` uses it as a
 * CI freshness gate. Keeping JSON as the truth + types as a derived artifact is the "best of both" the
 * design doc settled on (JSON truth + generated types, never fragile hand-written generics).
 *
 * The mapping is the WIRE/read shape: every field's JSON key is its `name` (verbatim — the engine never
 * snake_cases), an i64/decimal serialize as STRINGS (byte-exact big numbers), an enumeration narrows to a
 * literal union, and a nullable field is `name?: T | null`. Component/dynamiczone/relation/json map to
 * `unknown` for now (the nested-shape generation lands with relation+component files-path support).
 */

/** PascalCase a snake/kebab apiId for the interface name (`blog_post` -> `BlogPost`, `article` -> `Article`). */
function pascalCase(s: string): string {
  return s.replace(/(^|[_-])([a-zA-Z0-9])/g, (_m, _sep, c: string) => c.toUpperCase());
}

/** The TS type for one field, from its CmsType (+ enum members / media cardinality). */
function tsTypeOf(f: FieldSchema): string {
  switch (f.type) {
    case 'string':
    case 'text':
    case 'email':
    case 'uid':
    case 'uuid':
    case 'date':
    case 'datetime':
    case 'time':
      return 'string';
    case 'biginteger':
    case 'decimal':
      return 'string'; // i64 / numeric serialize as strings (byte-exact, no float precision loss)
    case 'enumeration': {
      const values = f.options?.values;
      return Array.isArray(values) && values.length > 0 ? values.map((v) => JSON.stringify(v)).join(' | ') : 'string';
    }
    case 'integer':
    case 'float':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'media':
      return f.options?.multiple ? 'number[]' : 'number'; // un-populated: the referenced files.id(s)
    case 'json':
    case 'array':
    case 'component':
    case 'component-repeatable':
    case 'dynamiczone':
    case 'relation':
      return 'unknown'; // nested-shape generation deferred with the relation+component files-path slice
  }
}

function fieldLine(f: FieldSchema): string {
  const nullable = f.options?.nullable ?? true;
  const t = tsTypeOf(f);
  return nullable ? `  ${f.name}?: ${t} | null;` : `  ${f.name}: ${t};`;
}

/**
 * Generate the `content-types.d.ts` text for a catalog of schemas (sorted by apiId for a deterministic,
 * diff-stable artifact). One interface per content-type: the system fields the read path always emits,
 * then the user fields in declared (wire) order.
 */
export function generateTypes(schemas: ContentTypeSchema[]): string {
  const header =
    '// GENERATED by conti — do not edit by hand. Source of truth: schema/*.json\n' +
    '// Regenerate with `conti gen:types` after editing a schema file.\n\n';

  const blocks = [...schemas]
    .sort((a, b) => (a.apiId < b.apiId ? -1 : a.apiId > b.apiId ? 1 : 0))
    .map((s) => {
      const lines: string[] = [`export interface ${pascalCase(s.apiId)} {`, '  id: number;'];
      if (s.options?.i18n) lines.push('  document_id: number;');
      lines.push('  created_at: string;', '  updated_at: string;');
      if (s.options?.draftAndPublish) lines.push('  published_at?: string | null;');
      if (s.options?.i18n) lines.push('  locale: string;');
      for (const f of s.fields) lines.push(fieldLine(f));
      lines.push('}');
      return lines.join('\n');
    });

  return header + blocks.join('\n\n') + '\n';
}
